"""empty message

Revision ID: 80fb1836d43d
Revises: 695c368e2998
Create Date: 2021-09-18 21:00:20.254917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fb1836d43d'
down_revision = '695c368e2998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testing')
    # ### end Alembic commands ###
